resolver: lts-18.13
packages:
  - katip
  - katip-elasticsearch
  - katip-datadog
  - katip-logzio
extra-deps:
  # ghc 8.8 support
  - github: bitemyapp/bloodhound
    commit: 358bf61c1a9504d42d7614fd8385fbf5e03d73d6
allow-newer: true
flags:
  katip:
    lib-Werror: true
  katip-elasticsearch:
    lib-Werror: true
  katip-datadog:
    lib-Werror: true
  katip-logzio:
    lib-Werror: true
