resolver: lts-18.13
extra-deps:
  # ghc 8.8 support
  - github: bitemyapp/bloodhound
    commit: 358bf61c1a9504d42d7614fd8385fbf5e03d73d6
allow-newer: true
flags:
  katip-elasticsearch:
    lib-Werror: true
